# Generated by Django 3.2.25 on 2025-05-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='content_object',
        ),
    ]
